### PR TITLE
Add Background to file property tab so aliases aren't invisible

### PR DESCRIPTION
**Pull request by WAS-D**
uhhhhhh yeah i just got fed up with not being able to see my aliases in the property menu instead of in-editor because they're basically invisible being the same colour as the background so here's a jank fix that doesn't change much

### CODE REVIEW

**Comment by seanwcom** [comment]
I'm not quite sure where/what the problem is ... in my screenshot everything appears to show up. Let me know what you're not seeing and I'll make adjustments. I won't merge these changes though because the theme.css file is rendered by compiling all the scss files from the source folder. No biggie though - if you can show a screenshot I'll try and reproduce the problem.

Here's what I'm seeing:

image

**Comment by seanwcom** [comment]
Oh, I just saw your posts in the Obsidian forum and you had screenshots there. I didn't realize you were talking about the sidebar. You're right - since it's a black and white theme it's a pain to get the styles right. I'd love to sit down one day and figure out a better way to do it. I've thought about just making the right side panel stay light colored. Anyway, for now I've put a change in that will make the properties panel more visible. There's a few more tweaks to make, but thanks for the feedback!

**Comment by WAS-D** [comment]
There's something else that didn't get merged. It's specifically to make sure that the vault switcher text doesn't blend into the background

**Comment by WAS-D** [comment]
`.workspace-drawer-vault-name {
    color: var(--nav-item-color);
}`

that snippet should fix it.

**Comment by WAS-D** [comment]
and also the properties disappear on hover and while editing them. that's why i added a white background, so they can be more visible since the properties fields in both the doccument and sidebar share the same css attributes

**Comment by seanwcom** [comment]
Thanks for the extra info - I just pushed a new version, hopefully makes everything else more visible in the properties panel. Also the vault name, and the suggestion popups.

**Pull request closed without merging**
